// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwAHLVadDJ3vanM4kC4b4ybnPaT8zpPs',
    appId: '1:678538988908:android:c836ff76f873106cfdf749',
    messagingSenderId: '678538988908',
    projectId: 'memories-through-lenses',
    databaseURL: 'https://memories-through-lenses-default-rtdb.firebaseio.com',
    storageBucket: 'memories-through-lenses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DPf3sDlfl7KNnx82Gn8Ky6urLhMSIxE',
    appId: '1:678538988908:ios:0b204c5f0f3fdaa5fdf749',
    messagingSenderId: '678538988908',
    projectId: 'memories-through-lenses',
    databaseURL: 'https://memories-through-lenses-default-rtdb.firebaseio.com',
    storageBucket: 'memories-through-lenses.appspot.com',
    iosBundleId: 'com.derek.memolens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DPf3sDlfl7KNnx82Gn8Ky6urLhMSIxE',
    appId: '1:678538988908:ios:2b5d5476316db57bfdf749',
    messagingSenderId: '678538988908',
    projectId: 'memories-through-lenses',
    databaseURL: 'https://memories-through-lenses-default-rtdb.firebaseio.com',
    storageBucket: 'memories-through-lenses.appspot.com',
    iosBundleId: 'com.example.memoriesThroughLenses',
  );
}
